### ISSUE TITLE
按照流程走了一遍

### ISSUE THREAD

**Issue by andrewngg** [WuLC/AmazonRobot#1]
有些部分不太明确， 

> Robot.py line 193

`user_name = conn.srandmember('user_name', 1)[0]`

这里为何寻找不到用户名？
是否还遗漏了部分的程序

**Comment by WuLC** [comment]
我没有写过什么流程，README 中已经简单说了各个文件的作用，需要使用请自行看懂代码

这是从数据库内随机取出某个用户姓名，需要先通过脚本获取，基本的脚本在`get_proxy_and_user_information`  目录下
